const DICTIONARY = {

    en: {
        MENU: "MENU",
        PLAY_GAME: "1. Play Game",
        SETTINGS: "2. Settings",
        EXIT_GAME: "3. Exit Game",
        CHOOSE_LANGUAGE: "Choose your preferred language",
        ENGLISH: "1. English",
        NORWEGIAN: "2. Norwegian",
        CHOOSE_GAME_MODE: "Which game mode would you like to play?",
        PVP: "1. Player vs Player",
        PVC: "2. Player vs Computer",
        WINNER_IS: "Winner is player ",
        DRAW: "It's a draw!",
        GAME_OVER: "GAME OVER",
        PLAYER_1: "one",
        PLAYER_2: "two",
        COMPUTER: "computer",
        PLAYER: "Player ",
        YOUR_TURN: " it is your turn",
        PLACE_MARK: "Place your mark at: ",
        PLAY_AGAIN_QUESTION: "Play again (YES/no)? ",
        CONFIRM: "y",

    },
    no: {
        MENU: "MENY",
        PLAY_GAME: "1. Spill",
        SETTINGS: "2. Innstillinger",
        EXIT_GAME: "3. Avslutt Spill",
        CHOOSE_LANGUAGE: "Velg ditt foretrukkete språk",
        ENGLISH: "1. Engelsk",
        NORWEGIAN: "2. Norwegian",
        CHOOSE_GAME_MODE: "Hvilken spillmodus ønsker du å spille?",
        PVP: "1. Spiller mot Spiller",
        PVC: "2. Spiller mot Datamaskin",
        WINNER_IS: "Vinneren er spiller ",
        DRAW: "Det ble uavgjort!",
        GAME_OVER: "SPILLET ER OVER",
        PLAYER_1: "en",
        PLAYER_2: "to",
        COMPUTER: "datamaskin",
        PLAYER: "Spiller ",
        YOUR_TURN: " det er din tur",
        PLACE_MARK: "Plasser ditt merke : ",
        PLAY_AGAIN_QUESTION: "Spille en gang til (Ja/nei)? ",
        CONFIRM: "j",
    }
}

export default DICTIONARY;