const DICTIONARY = {

    en: {
        MENU: "MENU",
        PLAY_GAME: "1. Play Game",
        SETTINGS: "2. Settings",
        EXIT_GAME: "3. Exit Game",
        CHOOSE_LANGUAGE: "Choose your preferred language",
        ENGLISH: "1. English",
        NORWEGIAN: "2. Norwegian",
        GERMAN: "3. German",
        SPANISH: "4. Spanish",
        CHOOSE_GAME_MODE: "Which game mode would you like to play?",
        PVP: "1. Player vs Player",
        PVC: "2. Player vs Computer",
        WINNER_IS: "Winner is player ",
        DRAW: "It's a draw!",
        GAME_OVER: "GAME OVER",
        PLAYER_1: "one",
        PLAYER_2: "two",
        COMPUTER_WIN: "Winner is the computer",
        PLAYER: "Player ",
        YOUR_TURN: " it is your turn",
        PLACE_MARK: "Place your mark at: ",
        PLAY_AGAIN_QUESTION: "Play again (YES/no)? ",
        CONFIRM: "y",

    },
    no: {
        MENU: "MENY",
        PLAY_GAME: "1. Spill",
        SETTINGS: "2. Innstillinger",
        EXIT_GAME: "3. Avslutt Spill",
        CHOOSE_LANGUAGE: "Velg ditt foretrukkete språk",
        ENGLISH: "1. Engelsk",
        NORWEGIAN: "2. Norsk",
        GERMAN: "3. Tysk",
        SPANISH: "4. Spansk",
        CHOOSE_GAME_MODE: "Hvilken spillmodus ønsker du å spille?",
        PVP: "1. Spiller mot Spiller",
        PVC: "2. Spiller mot Datamaskin",
        WINNER_IS: "Vinneren er spiller ",
        DRAW: "Det ble uavgjort!",
        GAME_OVER: "SPILLET ER OVER",
        PLAYER_1: "en",
        PLAYER_2: "to",
        COMPUTER_WIN: "Vinneren er datamaskinen",
        PLAYER: "Spiller ",
        YOUR_TURN: " det er din tur",
        PLACE_MARK: "Plasser ditt merke: ",
        PLAY_AGAIN_QUESTION: "Spille en gang til (Ja/nei)? ",
        CONFIRM: "j",
    },
    de: {
        MENU: "MENÜ",
        PLAY_GAME: "1. Spielen",
        SETTINGS: "2. Einstellungen",
        EXIT_GAME: "3. Spiel beenden",
        CHOOSE_LANGUAGE: "Wähle deine bevorzugte Sprache",
        ENGLISH: "1. Englisch",
        NORWEGIAN: "2. Norwegisch",
        GERMAN: "3. Deutsch",
        SPANISH: "4. Spanisch",
        CHOOSE_GAME_MODE: "Welchen Spielmodus möchtest du spielen?",
        PVP: "1. Spieler gegen Spieler",
        PVC: "2. Spieler gegen Computer",
        WINNER_IS: "Der Gewinner ist Spieler ",
        DRAW: "Unentschieden!",
        GAME_OVER: "SPIEL VORBEI",
        PLAYER_1: "eins",
        PLAYER_2: "zwei",
        COMPUTER_WIN: "Der Gewinner ist der Computer",
        PLAYER: "Spieler",
        YOUR_TURN: " du bist am Zug",
        PLACE_MARK: "Setze dein Zeichen: ",
        PLAY_AGAIN_QUESTION: "Noch einmal spielen (Ja/Nein)? ",
        CONFIRM: "j"
    },
    sp: {
        MENU: "MENÚ",
        PLAY_GAME: "1. Jugar",
        SETTINGS: "2. Ajustes",
        EXIT_GAME: "3. Salir del juego",
        CHOOSE_LANGUAGE: "Elige tu idioma preferido",
        ENGLISH: "1. Inglés",
        NORWEGIAN: "2. Noruego",
        GERMAN: "3. Alemán",
        SPANISH: "4. Español",
        CHOOSE_GAME_MODE: "¿Qué modo de juego quieres jugar?",
        PVP: "1. Jugador contra jugador",
        PVC: "2. Jugador contra computadora",
        WINNER_IS: "El ganador es el jugador ",
        DRAW: "¡Empate!",
        GAME_OVER: "FIN DEL JUEGO",
        PLAYER_1: "uno",
        PLAYER_2: "dos",
        COMPUTER_WIN: "El ganador es la computadora",
        PLAYER: "Jugador",
        YOUR_TURN: " es tu turno",
        PLACE_MARK: "Coloca tu marca: ",
        PLAY_AGAIN_QUESTION: "¿Jugar otra vez (Sí/No)? ",
        CONFIRM: "s"
    }
}

export default DICTIONARY;